#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Type of the characteristic, e.g. skill, certification.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum BookAbleResourceCharacteristicType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Certification", 1)]
		Certification = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Skill", 0)]
		Skill = 1,
	}
}
#pragma warning restore CS1591
