#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Options to cascade closing cases
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum CascadeCaseClosurePreference
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Close all child cases when parent case is closed", 0)]
		CloseAllChildCasesWhenParentCaseIsClosed = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Don\'t allow parent case closure until all child cases are closed", 1)]
		DonTAllowParentCaseClosureUntilAllChildCasesAreClosed = 1,
	}
}
#pragma warning restore CS1591
