#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Select the option for converting the campaign response
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Convert_Campaign_Response_Option
	{
		
		/// <summary>
		/// Close response label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Close response", 3, null, "Close response label")]
		CloseResponse = 4,
		
		/// <summary>
		/// Convert to existing lead label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Convert to an existing lead", 1, null, "Convert to existing lead label")]
		ConvertToAnExistingLead = 2,
		
		/// <summary>
		/// Create lead label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Create a lead", 0, null, "Create lead label")]
		CreateALead = 1,
		
		/// <summary>
		/// Create sales entity label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Create a quote, order, or opportunity for an account or contact", 2, null, "Create sales entity label")]
		CreateAQuoteOrderOrOpportunityForAnAccountOrContact = 3,
	}
}
#pragma warning restore CS1591
