#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Type of  channel activities.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum ConvertRule_ChannelActivity
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Appointment", 2)]
		Appointment = 4201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Conversation", 12)]
		Conversation = 10797,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Copilot Transcript", 14)]
		CopilotTranscript = 11032,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customer Voice alert", 10)]
		CustomerVoiceAlert = 10688,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customer Voice survey invite", 9)]
		CustomerVoiceSurveyInvite = 10698,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customer Voice survey response", 11)]
		CustomerVoiceSurveyResponse = 10700,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email", 1)]
		Email = 4202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Invite Redemption", 6)]
		InviteRedemption = 10377,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Phone Call", 0)]
		PhoneCall = 4210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Portal Comment", 7)]
		PortalComment = 10378,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Service Activity", 8)]
		ServiceActivity = 4214,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Session", 13)]
		Session = 10814,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Social Activity", 4)]
		SocialActivity = 4216,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Task", 3)]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Teams chat", 5)]
		TeamsChat = 10228,
	}
}
#pragma warning restore CS1591
