#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Select the option for converting the campaign response to a lead
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Convert_Campaign_Response_To_Lead_Option
	{
		
		/// <summary>
		/// Disqualify Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Disqualify", 1, null, "Disqualify Label")]
		Disqualify = 2,
		
		/// <summary>
		/// Qualify Label
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Qualify and convert into the following records", 0, null, "Qualify Label")]
		QualifyAndConvertIntoTheFollowingRecords = 1,
	}
}
#pragma warning restore CS1591
