#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Convert_Campaign_Response_Options
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Close response", 3, "#0000ff")]
		CloseResponse = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Convert to an existing lead", 1, "#0000ff")]
		ConvertToAnExistingLead = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Create a lead", 0, "#0000ff")]
		CreateALead = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Create a quote, order, or opportunity for an account or contact", 2, "#0000ff")]
		CreateAQuoteOrderOrOpportunityForAnAccountOrContact = 2,
	}
}
#pragma warning restore CS1591
