#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Option set for the different possible forms to use for incident/case resolution
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum IncidentResolutionFormType
	{
		
		/// <summary>
		/// MFD
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Customizable dialog", 1, "#0000ff", "MFD")]
		CustomizableDialog = 2,
		
		/// <summary>
		/// Quick create form
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Quick create dialog", 2, "#0000ff", "Quick create form")]
		QuickCreateDialog = 3,
		
		/// <summary>
		/// MDD
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Standard dialog", 0, "#0000ff", "MDD")]
		StandardDialog = 1,
	}
}
#pragma warning restore CS1591
