#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Option set for different type of update Incidents/Cases after resolution
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum IncidentUpdateAfterResolution
	{
		
		/// <summary>
		/// Canceled cases
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Canceled cases", 2, "#0000ff", "Canceled cases")]
		CanceledCases = 2,
		
		/// <summary>
		/// Don't allow updates
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Don\'t allow updates", 0, "#0000ff", "Don\'t allow updates")]
		DonTAllowUpdates = 0,
		
		/// <summary>
		/// Resolved and canceled cases
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Resolved and canceled cases", 3, "#0000ff", "Resolved and canceled cases")]
		ResolvedAndCanceledCases = 3,
		
		/// <summary>
		/// Resolved cases
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Resolved cases", 1, "#0000ff", "Resolved cases")]
		ResolvedCases = 1,
	}
}
#pragma warning restore CS1591
