#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// List of Mobile Offline Enabled Entities.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MobileOfflineEnabledEntities
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Account", 0)]
		Account = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AccountLeads", 22)]
		Accountleads = 16,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Account Research Agent Trigger", 80)]
		AccountResearchAgentTrigger = 11093,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Account Research Result", 81)]
		AccountResearchResult = 11094,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Activity File Attachment", 12)]
		ActivityFileAttachment = 10227,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Appointment", 8)]
		Appointment = 4201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Attachment", 5)]
		Attachment = 1001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Case", 38)]
		Case = 112,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comparator Metadata", 97)]
		ComparatorMetadata = 11377,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Competitor", 65)]
		Competitor = 123,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Competitor Address", 56)]
		CompetitorAddress = 1004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Competitor Product", 57)]
		CompetitorProduct = 1006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Competitor Research Agent Trigger", 82)]
		CompetitorResearchAgentTrigger = 11095,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Connection", 41)]
		Connection = 3234,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Connection Role", 42)]
		ConnectionRole = 3231,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Contact", 1)]
		Contact = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ContactLeads", 23)]
		Contactleads = 22,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Copilot knowledge interaction", 77)]
		CopilotKnowledgeInteraction = 11031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Currency", 73)]
		Currency = 9105,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Disposition Code Category", 76)]
		DispositionCodeCategory = 10988,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email", 9)]
		Email = 4202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Entitlement", 34)]
		Entitlement = 9700,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Entitlement Contact", 35)]
		EntitlementContact = 7272,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Entitlement Product", 36)]
		EntitlementProduct = 6363,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Entitlement Template Product", 37)]
		EntitlementTemplateProduct = 4545,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Entity Attachment", 75)]
		EntityAttachment = 10742,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Evaluation Global Config", 78)]
		EvaluationGlobalConfig = 11078,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EventMainBusinessProcessFlow", 95)]
		Eventmainbusinessprocessflow = 11210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Event registration custom field", 98)]
		EventRegistrationCustomField = 11490,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Image Descriptor", 20)]
		ImageDescriptor = 1007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Incident KnowledgeBaseRecord", 39)]
		IncidentKnowledgebaserecord = 9931,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Invoice", 67)]
		Invoice = 1090,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Invoice Product", 68)]
		InvoiceProduct = 1091,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Alert", 43)]
		IotAlert = 10477,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Alert to Case Process", 55)]
		IotAlertToCaseProcess = 10493,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Device", 44)]
		IotDevice = 10478,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Device Category", 45)]
		IotDeviceCategory = 10479,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Device Command", 46)]
		IotDeviceCommand = 10480,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Device Command Definition", 47)]
		IotDeviceCommandDefinition = 10481,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Device Data History", 48)]
		IotDeviceDataHistory = 10482,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Device Property", 49)]
		IotDeviceProperty = 10483,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Device Registration History", 50)]
		IotDeviceRegistrationHistory = 10484,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Property Definition", 51)]
		IotPropertyDefinition = 10487,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Provider", 52)]
		IotProvider = 10488,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Provider Instance", 53)]
		IotProviderInstance = 10489,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IoT Settings", 54)]
		IotSettings = 10490,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Knowledge Article Attachment", 14)]
		KnowledgeArticleAttachment = 10242,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Knowledge Article Image", 13)]
		KnowledgeArticleImage = 10236,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Knowledge Harvest Job Record", 17)]
		KnowledgeHarvestJobRecord = 10250,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lead", 24)]
		Lead = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lead Agent Result", 83)]
		LeadAgentResult = 11098,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("LeadCompetitors", 58)]
		Leadcompetitors = 24,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lead Delink Result", 84)]
		LeadDelinkResult = 11099,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("LeadProduct", 59)]
		Leadproduct = 27,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lead to opportunity", 96)]
		LeadToOpportunity = 11321,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lead To Opportunity Sales Process", 60)]
		LeadToOpportunitySalesProcess = 954,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("msdyn_broadcastmessagebulkactionapiprivilege", 99)]
		MsdynBroadcastmessagebulkactionapiprivilege = 11612,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("msdyn_bulkassigntoqueueapiprivilege", 100)]
		MsdynBulkassigntoqueueapiprivilege = 11613,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("msdyn_bulkforcecloseapiprivilege", 101)]
		MsdynBulkforcecloseapiprivilege = 11614,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("msdyn_historicalcaseharvestbatch", 15)]
		MsdynHistoricalcaseharvestbatch = 10248,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("msdyn_historicalcaseharvestrun", 16)]
		MsdynHistoricalcaseharvestrun = 10249,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Note", 2)]
		Note = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Opportunity", 61)]
		Opportunity = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("OpportunityCompetitors", 62)]
		Opportunitycompetitors = 25,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Opportunity Product", 63)]
		OpportunityProduct = 1083,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Opportunity Ranker Mapping", 112)]
		OpportunityRankerMapping = 11752,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Opportunity Research Indicator", 113)]
		OpportunityResearchIndicator = 11754,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Opportunity Research User Interactions", 114)]
		OpportunityResearchUserInteractions = 11756,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Opportunity Sales Process", 64)]
		OpportunitySalesProcess = 953,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Order", 71)]
		Order = 1088,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Order Product", 72)]
		OrderProduct = 1089,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("OrganizationDataSyncFnoState", 18)]
		Organizationdatasyncfnostate = 10272,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("OrganizationDataSyncState", 19)]
		Organizationdatasyncstate = 10273,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Outreach Agent Result", 85)]
		OutreachAgentResult = 11101,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Outreach Trigger Agent", 86)]
		OutreachTriggerAgent = 11102,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PA Flow Run Tracker", 79)]
		PaFlowRunTracker = 11086,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Phone To Case Process", 40)]
		PhoneToCaseProcess = 952,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PowerPagesDDOSAlert", 21)]
		Powerpagesddosalert = 10421,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Price List", 29)]
		PriceList = 1022,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Price List Item", 30)]
		PriceListItem = 1026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Product", 25)]
		Product = 1024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Product Map", 74)]
		ProductMap = 10718,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Product Relationship", 31)]
		ProductRelationship = 1028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Property", 26)]
		Property = 1048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Property Association", 27)]
		PropertyAssociation = 1235,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Property Instance", 66)]
		PropertyInstance = 1333,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Property Option Set Item", 28)]
		PropertyOptionSetItem = 1049,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Qualification Agent Trigger", 87)]
		QualificationAgentTrigger = 11103,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Queue", 6)]
		Queue = 2020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Queue Item", 7)]
		QueueItem = 2029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Quote", 69)]
		Quote = 1084,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Quote Product", 70)]
		QuoteProduct = 1085,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("RCS Watermark", 115)]
		RcsWatermark = 11757,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 013e913bbc", 146)]
		ReserveEntity013E913bbc = 11837,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 04c3f68c70", 140)]
		ReserveEntity04C3f68c70 = 11809,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 0951fd7e2d", 117)]
		ReserveEntity0951Fd7e2d = 11767,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 127d7b451c", 116)]
		ReserveEntity127D7b451c = 11761,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 175607984a", 131)]
		ReserveEntity175607984A = 11797,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 17820b815e", 141)]
		ReserveEntity17820B815e = 11810,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 21b75c0d3f", 149)]
		ReserveEntity21B75c0d3f = 11839,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 29be3fb69a", 130)]
		ReserveEntity29Be3fb69a = 11796,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 3160c6c236", 94)]
		ReserveEntity3160C6c236 = 11174,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 375d15faf3", 119)]
		ReserveEntity375D15faf3 = 11770,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 3c6d713107", 128)]
		ReserveEntity3C6d713107 = 11794,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 3d6b6e87af", 109)]
		ReserveEntity3D6b6e87af = 11733,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 416d3649d0", 135)]
		ReserveEntity416D3649d0 = 11802,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 47e2b8b9f9", 137)]
		ReserveEntity47E2b8b9f9 = 11804,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 4dd0670d1c", 122)]
		ReserveEntity4Dd0670d1c = 11773,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 5149dacaad", 102)]
		ReserveEntity5149Dacaad = 11666,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 55e07ae87d", 151)]
		ReserveEntity55E07ae87d = 11841,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 57850f0bf9", 125)]
		ReserveEntity57850F0bf9 = 11790,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 62fec84b6d", 120)]
		ReserveEntity62Fec84b6d = 11771,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 63a3141495", 127)]
		ReserveEntity63A3141495 = 11792,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 64733fd012", 129)]
		ReserveEntity64733Fd012 = 11795,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 690ae84988", 91)]
		ReserveEntity690Ae84988 = 11118,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 6c3c889b11", 92)]
		ReserveEntity6C3c889b11 = 11138,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 6d09446496", 132)]
		ReserveEntity6D09446496 = 11799,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 85d66c6615", 152)]
		ReserveEntity85D66c6615 = 11852,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 89f58996e4", 145)]
		ReserveEntity89F58996e4 = 11817,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 8d70b814a8", 124)]
		ReserveEntity8D70b814a8 = 11788,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 8ddefb0475", 104)]
		ReserveEntity8Ddefb0475 = 11713,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 8e2b80baa9", 148)]
		ReserveEntity8E2b80baa9 = 11838,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 919cf542d8", 153)]
		ReserveEntity919Cf542d8 = 11854,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity 9aa0218416", 150)]
		ReserveEntity9Aa0218416 = 11840,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity a148867e5b", 107)]
		ReserveEntityA148867e5b = 11746,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity a43f888470", 105)]
		ReserveEntityA43f888470 = 11715,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity a86a69fb71", 108)]
		ReserveEntityA86a69fb71 = 11747,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity b15d486c03", 118)]
		ReserveEntityB15d486c03 = 11769,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity bf5794cc59", 147)]
		ReserveEntityBf5794cc59 = 11818,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity cf00ef8392", 121)]
		ReserveEntityCf00ef8392 = 11772,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity cfc9041f58", 154)]
		ReserveEntityCfc9041f58 = 11855,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity e4fb71653e", 136)]
		ReserveEntityE4fb71653e = 11803,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity e6e32efc47", 139)]
		ReserveEntityE6e32efc47 = 11807,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity ea26439b6c", 93)]
		ReserveEntityEa26439b6c = 11156,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity f37d7985a4", 143)]
		ReserveEntityF37d7985a4 = 11812,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity f5f031bfce", 134)]
		ReserveEntityF5f031bfce = 11801,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity f75460238d", 103)]
		ReserveEntityF75460238d = 11705,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity f91d70564a", 138)]
		ReserveEntityF91d70564a = 11806,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity f93ebf4366", 126)]
		ReserveEntityF93ebf4366 = 11791,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity fa9498a648", 133)]
		ReserveEntityFa9498a648 = 11800,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity fb4e8c27fe", 142)]
		ReserveEntityFb4e8c27fe = 11813,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity fd0c018bb0", 123)]
		ReserveEntityFd0c018bb0 = 11787,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Reserve entity fd62468f3a", 106)]
		ReserveEntityFd62468f3a = 11732,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SalesAgentUsage", 88)]
		Salesagentusage = 11105,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Shorturl", 144)]
		Shorturl = 11835,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SLA KPI Instance", 11)]
		SlaKpiInstance = 9752,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Stakeholder Research Output", 89)]
		StakeholderResearchOutput = 11106,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Summary Synthesizer Agent Trigger", 110)]
		SummarySynthesizerAgentTrigger = 11750,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Target Customer Profile Prefill Agent Result", 90)]
		TargetCustomerProfilePrefillAgentResult = 11107,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("TargetCustomerProfilePrefillAgentTrigger", 111)]
		Targetcustomerprofileprefillagenttrigger = 11751,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Task", 10)]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Team", 4)]
		Team = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Unit", 32)]
		Unit = 1055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Unit Group", 33)]
		UnitGroup = 1056,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("User", 3)]
		User = 8,
	}
}
#pragma warning restore CS1591
