#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Denotes the mode of consultation a participant has in a conversation
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_ConsultModeType
	{
		
		/// <summary>
		/// Chat
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Chat", 0, null, "Chat")]
		Chat = 0,
		
		/// <summary>
		/// Chat And Voice
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Chat And Voice", 1, null, "Chat And Voice")]
		ChatAndVoice = 1,
		
		/// <summary>
		/// Voice
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Voice", 2, null, "Voice")]
		Voice = 2,
	}
}
#pragma warning restore CS1591
