#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Available list of calling session event reason options
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_OCCallSessionEvenTreasons
	{
		
		/// <summary>
		/// Accepted
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Accepted", 19, "#0000ff", "Accepted")]
		Accepted = 192350019,
		
		/// <summary>
		/// AgentConversationJoin
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentConversationJoin", 40, "#0000ff", "AgentConversationJoin")]
		Agentconversationjoin = 192350041,
		
		/// <summary>
		/// AgentDisconnected
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentDisconnected", 10, "#0000ff", "AgentDisconnected")]
		Agentdisconnected = 192350010,
		
		/// <summary>
		/// AgentEndConsult
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentEndConsult", 31, "#0000ff", "AgentEndConsult")]
		Agentendconsult = 192350032,
		
		/// <summary>
		/// AgentEndConversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentEndConversation", 30, "#0000ff", "AgentEndConversation")]
		Agentendconversation = 192350030,
		
		/// <summary>
		/// AgentGroupTransfer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentGroupTransfer", 47, "#0000ff", "AgentGroupTransfer")]
		Agentgrouptransfer = 192350050,
		
		/// <summary>
		/// AgentInviteRejected
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentInviteRejected", 8, "#0000ff", "AgentInviteRejected")]
		Agentinviterejected = 192350008,
		
		/// <summary>
		/// AgentInviteTimeout
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentInviteTimeout", 9, "#0000ff", "AgentInviteTimeout")]
		Agentinvitetimeout = 192350009,
		
		/// <summary>
		/// AgentMonitor
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentMonitor", 39, "#0000ff", "AgentMonitor")]
		Agentmonitor = 192350040,
		
		/// <summary>
		/// AgentTimeout
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentTimeout", 11, "#0000ff", "AgentTimeout")]
		Agenttimeout = 192350011,
		
		/// <summary>
		/// AgentTransfer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentTransfer", 0, "#0000ff", "AgentTransfer")]
		Agenttransfer = 192350001,
		
		/// <summary>
		/// AgentTransferred
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AgentTransferred", 12, "#0000ff", "AgentTransferred")]
		Agenttransferred = 192350012,
		
		/// <summary>
		/// AssignToAgentBySupervisor  
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AssignToAgentBySupervisor  ", 26, "#0000ff", "AssignToAgentBySupervisor  ")]
		Assigntoagentbysupervisor = 192350026,
		
		/// <summary>
		/// AssignToQueueBySupervisor  
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AssignToQueueBySupervisor  ", 27, "#0000ff", "AssignToQueueBySupervisor  ")]
		Assigntoqueuebysupervisor = 192350027,
		
		/// <summary>
		/// AutoAccept
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AutoAccept", 6, "#0000ff", "AutoAccept")]
		Autoaccept = 192350006,
		
		/// <summary>
		/// AutoAccepted
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AutoAccepted", 20, "#0000ff", "AutoAccepted")]
		Autoaccepted = 192350020,
		
		/// <summary>
		/// BotCallFailureEndConversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("BotCallFailureEndConversation", 42, "#0000ff", "BotCallFailureEndConversation")]
		Botcallfailureendconversation = 192350043,
		
		/// <summary>
		/// BotCallFailureEscalate
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("BotCallFailureEscalate", 45, "#0000ff", "BotCallFailureEscalate")]
		Botcallfailureescalate = 192350046,
		
		/// <summary>
		/// BotCallFailureExternalTransfer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("BotCallFailureExternalTransfer", 43, "#0000ff", "BotCallFailureExternalTransfer")]
		Botcallfailureexternaltransfer = 192350044,
		
		/// <summary>
		/// BotCallFailurePromptAndEscalate
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("BotCallFailurePromptAndEscalate", 44, "#0000ff", "BotCallFailurePromptAndEscalate")]
		Botcallfailurepromptandescalate = 192350045,
		
		/// <summary>
		/// BotEndConversation 
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("BotEndConversation ", 25, "#0000ff", "BotEndConversation ")]
		Botendconversation = 192350025,
		
		/// <summary>
		/// BotTransferSession 
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("BotTransferSession ", 24, "#0000ff", "BotTransferSession ")]
		Bottransfersession = 192350024,
		
		/// <summary>
		/// Closed
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Closed", 7, "#0000ff", "Closed")]
		Closed = 192350007,
		
		/// <summary>
		/// Consult
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Consult", 38, "#0000ff", "Consult")]
		Consult = 192350039,
		
		/// <summary>
		/// ConversationExpired
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ConversationExpired", 37, "#0000ff", "ConversationExpired")]
		Conversationexpired = 192350038,
		
		/// <summary>
		/// CustomerDisconnect
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CustomerDisconnect", 14, "#0000ff", "CustomerDisconnect")]
		Customerdisconnect = 192350014,
		
		/// <summary>
		/// CustomerEndConversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CustomerEndConversation", 29, "#0000ff", "CustomerEndConversation")]
		Customerendconversation = 192350029,
		
		/// <summary>
		/// CustomerReconnect
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CustomerReconnect", 46, "#0000ff", "CustomerReconnect")]
		Customerreconnect = 192350049,
		
		/// <summary>
		/// CustomerRejoin
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CustomerRejoin", 28, "#0000ff", "CustomerRejoin")]
		Customerrejoin = 192350028,
		
		/// <summary>
		/// CustomerTimeout
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CustomerTimeout", 13, "#0000ff", "CustomerTimeout")]
		Customertimeout = 192350013,
		
		/// <summary>
		/// Default
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Default", 48, "#0000ff", "Default")]
		Default = 192350000,
		
		/// <summary>
		/// Disconnect
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Disconnect", 21, "#0000ff", "Disconnect")]
		Disconnect = 192350021,
		
		/// <summary>
		/// End
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("End", 23, "#0000ff", "End")]
		End = 192350023,
		
		/// <summary>
		/// Escalated
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Escalated", 16, "#0000ff", "Escalated")]
		Escalated = 192350016,
		
		/// <summary>
		/// ForceClose
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ForceClose", 32, "#0000ff", "ForceClose")]
		Forceclose = 192350033,
		
		/// <summary>
		/// OverflowAssignToQueue
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("OverflowAssignToQueue", 35, "#0000ff", "OverflowAssignToQueue")]
		Overflowassigntoqueue = 192350036,
		
		/// <summary>
		/// OverflowEndConversation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("OverflowEndConversation", 34, "#0000ff", "OverflowEndConversation")]
		Overflowendconversation = 192350035,
		
		/// <summary>
		/// OverflowQueueTransfer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("OverflowQueueTransfer", 33, "#0000ff", "OverflowQueueTransfer")]
		Overflowqueuetransfer = 192350034,
		
		/// <summary>
		/// PostchatSurvey
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PostchatSurvey", 4, "#0000ff", "PostchatSurvey")]
		Postchatsurvey = 192350004,
		
		/// <summary>
		/// PreChatSurvey
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PreChatSurvey", 3, "#0000ff", "PreChatSurvey")]
		Prechatsurvey = 192350003,
		
		/// <summary>
		/// Preview
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Preview", 41, "#0000ff", "Preview")]
		Preview = 192350042,
		
		/// <summary>
		/// QueueTransfer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("QueueTransfer", 2, "#0000ff", "QueueTransfer")]
		Queuetransfer = 192350002,
		
		/// <summary>
		/// Rejected
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Rejected", 17, "#0000ff", "Rejected")]
		Rejected = 192350017,
		
		/// <summary>
		/// SessionEndAfterWrapUp
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SessionEndAfterWrapUp", 36, "#0000ff", "SessionEndAfterWrapUp")]
		Sessionendafterwrapup = 192350037,
		
		/// <summary>
		/// SessionTimeout
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SessionTimeout", 15, "#0000ff", "SessionTimeout")]
		Sessiontimeout = 192350015,
		
		/// <summary>
		/// Default
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SupervisorTransferToAgent", 1, "#0000ff", "Default")]
		Supervisortransfertoagent = 192350031,
		
		/// <summary>
		/// TimedOut
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("TimedOut", 18, "#0000ff", "TimedOut")]
		Timedout = 192350018,
		
		/// <summary>
		/// Timeout
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Timeout", 22, "#0000ff", "Timeout")]
		Timeout = 192350022,
		
		/// <summary>
		/// UserAccept
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("UserAccept", 5, "#0000ff", "UserAccept")]
		Useraccept = 192350005,
	}
}
#pragma warning restore CS1591
