#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Time Range Units
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_TimeRangeType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Days", 1, "#0000ff")]
		Days = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Hours", 0, "#0000ff")]
		Hours = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Latest", 2, "#0000ff")]
		Latest = 192350002,
	}
}
#pragma warning restore CS1591
