#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Stores the list of event types for message templates.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_OCMessageTemplateTrigger
	{
		
		/// <summary>
		/// Outside 24-hour conversation window
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Outside 24-hour conversation window", 0, "#0000ff", "Outside 24-hour conversation window")]
		Outside24HourConversationWindow = 1,
	}
}
#pragma warning restore CS1591
