#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Copilot product type picker
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_ViVaCopilotType
	{
		
		/// <summary>
		/// Represents records related to Sales Copilot
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Copilot for Sales", 0, null, "Represents records related to Sales Copilot")]
		CopilotForSales = 10000,
		
		/// <summary>
		/// Represents records related to Service Copilot
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Copilot for Service", 1, null, "Represents records related to Service Copilot")]
		CopilotForService = 10001,
		
		/// <summary>
		/// Represents records that are shared across different Copilot types
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Shared", 2, null, "Represents records that are shared across different Copilot types")]
		Shared = 11000,
	}
}
#pragma warning restore CS1591
