#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Dynamics 365 Languages
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_LanguageCodes
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("English", 0, "#0000ff", "", "en-us")]
		English = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Simplified Chinese", 2)]
		SimplifiedChinese = 372120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Traditional Chinese", 1)]
		TraditionalChinese = 372120001,
	}
}
#pragma warning restore CS1591
