#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Option set for type of language.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_OCRichObject_Msdyn_Locale
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-SA", 1, "#0000ff")]
		ArSa = 1025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("bg-BG", 4, "#0000ff")]
		BgBg = 1026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ca-ES", 3, "#0000ff")]
		CaEs = 1027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("cs-CZ", 6, "#0000ff")]
		CsCz = 1029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("da-DK", 7, "#0000ff")]
		DaDk = 1030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("de-DE", 13, "#0000ff")]
		DeDe = 1031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("el-GR", 14, "#0000ff")]
		ElGr = 1032,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("en-US", 0, "#0000ff")]
		EnUs = 1033,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("es-ES", 36, "#0000ff")]
		EsEs = 3082,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("et-EE", 9, "#0000ff")]
		EtEe = 1061,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("eu-ES", 2, "#0000ff")]
		EuEs = 1069,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("fi-FI", 10, "#0000ff")]
		FiFi = 1035,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("fr-FR", 11, "#0000ff")]
		FrFr = 1036,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("gl-ES", 12, "#0000ff")]
		GlEs = 1110,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("he-IL", 15, "#0000ff")]
		HeIl = 1037,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("hi-IN", 16, "#0000ff")]
		HiIn = 1081,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("hr-HR", 5, "#0000ff")]
		HrHr = 1050,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("hu-HU", 17, "#0000ff")]
		HuHu = 1038,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("id-ID", 19, "#0000ff")]
		IdId = 1057,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("it-IT", 18, "#0000ff")]
		ItIt = 1040,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ja-JP", 20, "#0000ff")]
		JaJp = 1041,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("kk-KZ", 21, "#0000ff")]
		KkKz = 1087,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ko-KR", 22, "#0000ff")]
		KoKr = 1042,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("lt-LT", 24, "#0000ff")]
		LtLt = 1063,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("lv-LV", 23, "#0000ff")]
		LvLv = 1062,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ms-MY", 25, "#0000ff")]
		MsMy = 1086,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("nb-NO", 26, "#0000ff")]
		NbNo = 1044,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("nl-NL", 8, "#0000ff")]
		NlNl = 1043,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("pl-PL", 27, "#0000ff")]
		PlPl = 1045,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("pt-BR", 28, "#0000ff")]
		PtBr = 1046,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("pt-PT", 29, "#0000ff")]
		PtPt = 2070,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ro-RO", 30, "#0000ff")]
		RoRo = 1048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ru-RU", 31, "#0000ff")]
		RuRu = 1049,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("sk-SK", 34, "#0000ff")]
		SkSk = 1051,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("sl-SI", 35, "#0000ff")]
		SlSi = 1060,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("sr-Cyrl-CS", 32, "#0000ff")]
		SrCyrlCs = 3098,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("sr-Latn-CS", 33, "#0000ff")]
		SrLatnCs = 2074,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("sv-SE", 37, "#0000ff")]
		SvSe = 1053,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("th-TH", 38, "#0000ff")]
		ThTh = 1054,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("tr-TR", 39, "#0000ff")]
		TrTr = 1055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("uk-UA", 40, "#0000ff")]
		UkUa = 1058,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("vi-VN", 41, "#0000ff")]
		ViVn = 1066,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("zh-CN", 42, "#0000ff")]
		ZhCn = 2052,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("zh-HK", 43, "#0000ff")]
		ZhHk = 3076,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("zh-TW", 44, "#0000ff")]
		ZhTw = 1028,
	}
}
#pragma warning restore CS1591
