#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Various scenario types
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_ScenarioType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ask a question", 0)]
		AskAQuestion = 100230201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Autonomous Case Create and Update", 17)]
		AutonomousCaseCreateAndUpdate = 100230218,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Case Closure", 23)]
		CaseClosure = 100230324,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Case Follow Up", 22)]
		CaseFollowUp = 100230323,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Case summary", 4)]
		CaseSummary = 100230205,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Chat Assist", 15)]
		ChatAssist = 100230216,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Collaborate with SMEs", 9)]
		CollaborateWithSmes = 100230210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Copilot", 3)]
		Copilot = 100230204,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Custom entity summary", 8)]
		CustomEntitySummary = 100230209,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Enrich record", 20)]
		EnrichRecord = 100230321,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inline Copilot for email", 10)]
		InlineCopilotForEmail = 100230211,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Intent Assist", 12)]
		IntentAssist = 100230213,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Knowledge draft assist", 7)]
		KnowledgeDraftAssist = 100230208,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("knowledge harvest", 13)]
		KnowledgeHarvest = 100230214,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Live conversation response", 1)]
		LiveConversationResponse = 100230202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Live conversation summary", 5)]
		LiveConversationSummary = 100230206,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Proactive Insights", 18)]
		ProactiveInsights = 100230219,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Quality Evaluation", 19)]
		QualityEvaluation = 100230220,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Resolution notes", 14)]
		ResolutionNotes = 100230215,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Resolve case", 21)]
		ResolveCase = 100230322,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Teams collaboration summary", 16)]
		TeamsCollaborationSummary = 100230217,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Timeline highlights", 6)]
		TimelineHighlights = 100230207,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Timeline next best actions", 11)]
		TimelineNextBestActions = 100230212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Write an email", 2)]
		WriteAnEmail = 100230203,
	}
}
#pragma warning restore CS1591
