#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Market type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MsdynCrm_Email_Template_Market_Type
	{
		
		/// <summary>
		/// B2B
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("B2B", 0, "#0000ff", "B2B")]
		B2b = 0,
		
		/// <summary>
		/// B2B & B2C
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("B2B & B2C", 2, "#0000ff", "B2B & B2C")]
		B2bB2c = 2,
		
		/// <summary>
		/// B2C
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("B2C", 1, "#0000ff", "B2C")]
		B2c = 1,
	}
}
#pragma warning restore CS1591
