#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// This option set is used to list different Field Data Formats.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_IotFieldDataFormat
	{
		
		/// <summary>
		/// The field directly contains the value.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Direct", 0, "#0000ff", "The field directly contains the value.")]
		Direct = 192350000,
		
		/// <summary>
		/// The field contains a JSON containing the value desired.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("JSON", 1, "#0000ff", "The field contains a JSON containing the value desired.")]
		Json = 192350001,
	}
}
#pragma warning restore CS1591
