#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MsdynCrm_GeoRegion
	{
		
		/// <summary>
		/// Argentina
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AR", 0, "#0000ff", "Argentina")]
		Ar = 192350024,
		
		/// <summary>
		/// China
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CN", 1, "#0000ff", "China")]
		Cn = 192350156,
		
		/// <summary>
		/// India
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("IN", 2, "#0000ff", "India")]
		In = 192350356,
		
		/// <summary>
		/// Other region
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 4, "#0000ff", "Other region")]
		Other = 192350000,
		
		/// <summary>
		/// Pakistan
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PK", 3, "#0000ff", "Pakistan")]
		Pk = 192350586,
	}
}
#pragma warning restore CS1591
