#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Report Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_AnalyticsReportType
	{
		
		/// <summary>
		/// Default
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Default", 0, "#0000ff", "Default")]
		Default = 192350000,
		
		/// <summary>
		/// Draft
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Draft", 2, "#0000ff", "Draft")]
		Draft = 192350002,
		
		/// <summary>
		/// Published
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Published", 1, "#0000ff", "Published")]
		Published = 192350001,
	}
}
#pragma warning restore CS1591
