#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Whether or not an automatically-generated attribute value or attribute values has been approved by your organanization's admin.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_ReviewStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Approved", 1, "#0000ff")]
		Approved = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dismissed", 2, "#0000ff")]
		Dismissed = 2,
		
		/// <summary>
		/// This means that the entity has not been reviewed by user
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not approved", 0, "#0000ff", "This means that the entity has not been reviewed by user")]
		NotApproved = 0,
	}
}
#pragma warning restore CS1591
