#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Out of the box (by default) Marketing automatically configures 3 Purpose Consents: 
	///
	///Commercial Communication 
	///Transactional Communication 
	///Tracking
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MsDynMkt_PurposeType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Commercial Communication", 0, "#0000ff")]
		CommercialCommunication = 534120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tracking", 2, "#0000ff")]
		Tracking = 534120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transactional Communication", 1, "#0000ff")]
		TransactionalCommunication = 534120001,
	}
}
#pragma warning restore CS1591
