#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Purpose
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MsdynCrm_Email_Template_Purpose
	{
		
		/// <summary>
		/// Abandoned shopping cart
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Abandoned shopping cart", 14, "#0000ff", "Abandoned shopping cart")]
		AbandonedShoppingCart = 15,
		
		/// <summary>
		/// Anniversary
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Anniversary", 20, "#0000ff", "Anniversary")]
		Anniversary = 21,
		
		/// <summary>
		/// Announcement
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Announcement", 1, "#0000ff", "Announcement")]
		Announcement = 2,
		
		/// <summary>
		/// Birthday
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Birthday", 2, "#0000ff", "Birthday")]
		Birthday = 3,
		
		/// <summary>
		/// Blog promotion
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Blog promotion", 3, "#0000ff", "Blog promotion")]
		BlogPromotion = 4,
		
		/// <summary>
		/// Content promotion
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Content promotion", 4, "#0000ff", "Content promotion")]
		ContentPromotion = 5,
		
		/// <summary>
		/// Double opt-in, email based confirmation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Double opt-in, email based confirmation", 22, "#0000ff", "Double opt-in, email based confirmation")]
		DoubleOptInEmailBasedConfirmation = 23,
		
		/// <summary>
		/// Event countdown
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Event countdown", 5, "#0000ff", "Event countdown")]
		EventCountdown = 6,
		
		/// <summary>
		/// Event or webinar invitation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Event or webinar invitation", 6, "#0000ff", "Event or webinar invitation")]
		EventOrWebinarInvitation = 7,
		
		/// <summary>
		/// Feedback request
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Feedback request", 19, "#0000ff", "Feedback request")]
		FeedbackRequest = 20,
		
		/// <summary>
		/// Follow-up
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Follow-up", 7, "#0000ff", "Follow-up")]
		FollowUp = 8,
		
		/// <summary>
		/// Holiday greetings
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Holiday greetings", 8, "#0000ff", "Holiday greetings")]
		HolidayGreetings = 9,
		
		/// <summary>
		/// Hospitality
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Hospitality", 10, "#0000ff", "Hospitality")]
		Hospitality = 11,
		
		/// <summary>
		/// Information
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Information", 9, "#0000ff", "Information")]
		Information = 10,
		
		/// <summary>
		/// Lead nurturing
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lead nurturing", 21, "#0000ff", "Lead nurturing")]
		LeadNurturing = 22,
		
		/// <summary>
		/// Newsletter
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Newsletter", 11, "#0000ff", "Newsletter")]
		Newsletter = 12,
		
		/// <summary>
		/// Post purchase
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Post purchase", 12, "#0000ff", "Post purchase")]
		PostPurchase = 13,
		
		/// <summary>
		/// Promotional (up-sell/cross-sell)
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Promotional (up-sell/cross-sell)", 13, "#0000ff", "Promotional (up-sell/cross-sell)")]
		PromotionalUpSellCrossSell = 14,
		
		/// <summary>
		/// Structural
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Structural", 0, "#0000ff", "Structural")]
		Structural = 0,
		
		/// <summary>
		/// Thank you
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Thank you", 15, "#0000ff", "Thank you")]
		ThankYou = 16,
		
		/// <summary>
		/// Upcoming event
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Upcoming event", 16, "#0000ff", "Upcoming event")]
		UpcomingEvent = 17,
		
		/// <summary>
		/// Welcome
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Welcome", 17, "#0000ff", "Welcome")]
		Welcome = 18,
		
		/// <summary>
		/// Win-back/re-engage
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Win-back/re-engage", 18, "#0000ff", "Win-back/re-engage")]
		WinBackReEngage = 19,
	}
}
#pragma warning restore CS1591
