#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Defines routing status
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_Msdyn_UnifiedRoutingRun_Msdyn_RoutingStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent assignment - completed", 6, "#0000ff")]
		AgentAssignmentCompleted = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Intake rules - completed", 0, "#0000ff")]
		IntakeRulesCompleted = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Queue: Assignment rules - completed", 5, "#0000ff")]
		QueueAssignmentRulesCompleted = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Queue: Assignment selection rules - completed", 4, "#0000ff")]
		QueueAssignmentSelectionRulesCompleted = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Queue: Prioritization rules - completed", 3, "#0000ff")]
		QueuePrioritizationRulesCompleted = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Workstream: Classification rules - processing...", 1, "#0000ff")]
		WorkstreamClassificationRulesProcessing = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Workstream: Route-to-queue rules - completed", 2, "#0000ff")]
		WorkstreamRouteToQueueRulesCompleted = 100000002,
	}
}
#pragma warning restore CS1591
