#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Defines the step type for routing configuration
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_RoutingConfigurationStepType
	{
		
		/// <summary>
		/// Identifies the agent group for the work-item
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent Group identification", 3, "#0000ff", "Identifies the agent group for the work-item")]
		AgentGroupIdentification = 192350003,
		
		/// <summary>
		/// Enriches the work-item
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Enrichment", 0, "#0000ff", "Enriches the work-item")]
		Enrichment = 192350000,
		
		/// <summary>
		/// Identifies the queue for the work-item
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Queue identification", 2, "#0000ff", "Identifies the queue for the work-item")]
		QueueIdentification = 192350002,
		
		/// <summary>
		/// Identifies the skills for the work-item
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Skill identification", 1, "#0000ff", "Identifies the skills for the work-item")]
		SkillIdentification = 192350001,
	}
}
#pragma warning restore CS1591
