#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Actions to be taken on bot failure
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_BotFailureActionType
	{
		
		/// <summary>
		/// Play a prompt and escalate
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Prompt and Escalate", 2, null, "Play a prompt and escalate")]
		PromptAndEscalate = 192350002,
		
		/// <summary>
		/// Play a prompt and transfer to an external number
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Prompt and External Transfer", 1, null, "Play a prompt and transfer to an external number")]
		PromptAndExternalTransfer = 192350001,
		
		/// <summary>
		/// Play a prompt and hang up the call
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Prompt and Hang Up", 0, null, "Play a prompt and hang up the call")]
		PromptAndHangUp = 192350000,
		
		/// <summary>
		/// Play wait music and escalate
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Wait Music and Escalate", 3, null, "Play wait music and escalate")]
		WaitMusicAndEscalate = 192350003,
	}
}
#pragma warning restore CS1591
