#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_EvaluationMethod
	{
		
		/// <summary>
		/// AI completes evaluation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AI agent", 1, null, "AI completes evaluation")]
		AiAgent = 700610001,
		
		/// <summary>
		/// person reviews the AI evaluation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AI assisted", 0, null, "person reviews the AI evaluation")]
		AiAssisted = 700610000,
		
		/// <summary>
		/// evaluation by a person
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Manual", 2, null, "evaluation by a person")]
		Manual = 700610002,
	}
}
#pragma warning restore CS1591
