#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Indicates model's training status
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_MlTrainingStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Draft", 8)]
		Draft = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Loading Data", 9)]
		LoadingData = 326340008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Publish completed", 2)]
		PublishCompleted = 326340003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Publish config created", 7)]
		PublishConfigCreated = 326340007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Publish failed", 1)]
		PublishFailed = 326340002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Publish in progress", 0)]
		PublishInProgress = 326340000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Train config created", 3)]
		TrainConfigCreated = 326340001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Training completed", 6)]
		TrainingCompleted = 326340006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Training failed", 4)]
		TrainingFailed = 326340004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Training in progress", 5)]
		TrainingInProgress = 326340005,
	}
}
#pragma warning restore CS1591
