#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Show desktop notifications
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_DesktopNotificationSettings
	{
		
		/// <summary>
		/// Never
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Never", 0, "#AA0000", "Never")]
		Never = 100000002,
		
		/// <summary>
		/// When app is in background
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("When app is in background", 1, "#000000", "When app is in background")]
		WhenAppIsInBackground = 100000003,
	}
}
#pragma warning restore CS1591
