#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Defines the type for ML model
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_MlModelType
	{
		
		/// <summary>
		/// Routing using Effort ML model
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Effort based", 2, null, "Routing using Effort ML model")]
		EffortBased = 192350002,
		
		/// <summary>
		/// Routing using Sentiment ML model
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sentiment based", 1, null, "Routing using Sentiment ML model")]
		SentimentBased = 192350001,
		
		/// <summary>
		/// Skill identification using ML model
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Skill based", 0, null, "Skill identification using ML model")]
		SkillBased = 192350000,
	}
}
#pragma warning restore CS1591
