#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// The last session outcome reason options.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_LastSessionOutcomeReason
	{
		
		/// <summary>
		/// Indicates that a creator or author of the Bot configures the bot to transfer to an agent.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent Transfer Configured By Author", 7, null, "Indicates that a creator or author of the Bot configures the bot to transfer to a" +
			"n agent.")]
		AgentTransferConfiguredByAuthor = 419580007,
		
		/// <summary>
		/// Indicates that in Question node maximum attempts are reached but Bot could not help and proposes to transfer to an agent.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent Transfer From Question Max Attempts", 8, null, "Indicates that in Question node maximum attempts are reached but Bot could not he" +
			"lp and proposes to transfer to an agent.")]
		AgentTransferFromQuestionMaxAttempts = 419580008,
		
		/// <summary>
		/// Indicates that an actual user of the Bot decides to raise an agent transfer.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent Transfer Requested By User", 5, null, "Indicates that an actual user of the Bot decides to raise an agent transfer.")]
		AgentTransferRequestedByUser = 419580005,
		
		/// <summary>
		/// Indicates an agent transfer without errors.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Agent Transfer Without Error", 4, null, "Indicates an agent transfer without errors.")]
		AgentTransferWithoutError = 419580004,
		
		/// <summary>
		/// Indicates a no error found.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("No Error", 0, null, "Indicates a no error found.")]
		NoError = 419580000,
		
		/// <summary>
		/// Indicates an exit due to issue resolution.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Resolved", 6, null, "Indicates an exit due to issue resolution.")]
		Resolved = 419580006,
		
		/// <summary>
		/// Indicates that a system error occurred.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("System Error", 2, null, "Indicates that a system error occurred.")]
		SystemError = 419580002,
		
		/// <summary>
		/// Indicates an error from the user
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("User Error", 1, null, "Indicates an error from the user")]
		UserError = 419580001,
		
		/// <summary>
		/// Indicates a normal session user exit.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("User Exit", 3, null, "Indicates a normal session user exit.")]
		UserExit = 419580003,
	}
}
#pragma warning restore CS1591
