#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MsdynCrm_Days
	{
		
		/// <summary>
		/// Friday
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Friday", 4, "#0000ff", "Friday")]
		Friday = 192350004,
		
		/// <summary>
		/// Monday
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Monday", 0, "#0000ff", "Monday")]
		Monday = 192350000,
		
		/// <summary>
		/// Saturday
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Saturday", 5, "#0000ff", "Saturday")]
		Saturday = 192350005,
		
		/// <summary>
		/// Sunday
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sunday", 6, "#0000ff", "Sunday")]
		Sunday = 192350006,
		
		/// <summary>
		/// Thursday
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Thursday", 3, "#0000ff", "Thursday")]
		Thursday = 192350003,
		
		/// <summary>
		/// Tuesday
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tuesday", 1, "#0000ff", "Tuesday")]
		Tuesday = 192350001,
		
		/// <summary>
		/// Wednesday
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Wednesday", 2, "#0000ff", "Wednesday")]
		Wednesday = 192350002,
	}
}
#pragma warning restore CS1591
