#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Agent Input Languages
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_AgentInputLanguage
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Arabic - Saudi Arabia", 1, "#0000ff", "", "ar-SA")]
		ArabicSaudiArabia = 1025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Basque - Spain", 2, "#0000ff", "", "eu-ES")]
		BasqueSpain = 1069,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Bulgarian - Bulgaria", 4, "#0000ff", "", "bg-BG")]
		BulgarianBulgaria = 1026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Catalan - Spain", 3, "#0000ff", "", "ca-ES")]
		CatalanSpain = 1027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Chinese - China", 42, "#0000ff", "", "zh-CN")]
		ChineseChina = 2052,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Chinese - Hong Kong", 43, "#0000ff", "", "zh-HK")]
		ChineseHongKong = 3076,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Croatian - Croatia", 5, "#0000ff", "", "hr-HR")]
		CroatianCroatia = 1050,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Czech - Czech Republic", 6, "#0000ff", "", "cs-CZ")]
		CzechCzechRepublic = 1029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Danish - Denmark", 7, "#0000ff", "", "da-DK")]
		DanishDenmark = 1030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dutch - Netherlands", 8, "#0000ff", "", "nl-NL")]
		DutchNetherlands = 1043,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("English - United States", 0, "#0000ff", "", "en-US")]
		EnglishUnitedStates = 1033,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Estonian - Estonia", 9, "#0000ff", "", "et-EE")]
		EstonianEstonia = 1061,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Finnish - Finland", 10, "#0000ff", "", "fi-FI")]
		FinnishFinland = 1035,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("French - France", 11, "#0000ff", "", "fr-FR")]
		FrenchFrance = 1036,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Galician - Spain", 12, "#0000ff", "", "gl-ES")]
		GalicianSpain = 1110,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("German - Germany", 13, "#0000ff", "", "de-DE")]
		GermanGermany = 1031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Greek - Greece", 14, "#0000ff", "", "el-GR")]
		GreekGreece = 1032,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Hebrew - Israel", 15, "#0000ff", "", "he-IL")]
		HebrewIsrael = 1037,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Hindi - India", 16, "#0000ff", "", "hi-IN")]
		HindiIndia = 1081,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Hungarian - Hungary", 17, "#0000ff", "", "hu-HU")]
		HungarianHungary = 1038,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Indonesian - Indonesia", 19, "#0000ff", "", "id-ID")]
		IndonesianIndonesia = 1057,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Italian - Italy", 18, "#0000ff", "", "it-IT")]
		ItalianItaly = 1040,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Japanese - Japan", 20, "#0000ff", "", "ja-JP")]
		JapaneseJapan = 1041,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Kazakh - Kazakhstan", 21, "#0000ff", "", "kk-KZ")]
		KazakhKazakhstan = 1087,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Korean - Korea", 22, "#0000ff", "", "ko-KR")]
		KoreanKorea = 1042,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Latvian - Latvia", 23, "#0000ff", "", "lv-LV")]
		LatvianLatvia = 1062,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lithuanian - Lithuania", 24, "#0000ff", "", "lt-LT")]
		LithuanianLithuania = 1063,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Malay - Malaysia", 25, "#0000ff", "", "ms-MY")]
		MalayMalaysia = 1086,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Norwegian Bokmal - Norway", 26, "#0000ff", "", "nb-NO")]
		NorwegianBokmalNorway = 1044,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Polish - Poland", 27, "#0000ff", "", "pl-PL")]
		PolishPoland = 1045,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Portuguese - Brazil", 28, "#0000ff", "", "pt-BR")]
		PortugueseBrazil = 1046,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Portuguese - Portugal", 29, "#0000ff", "", "pt-PT")]
		PortuguesePortugal = 2070,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Romanian - Romania", 30, "#0000ff", "", "ro-RO")]
		RomanianRomania = 1048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Russian - Russia", 31, "#0000ff", "", "ru-RU")]
		RussianRussia = 1049,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Serbian (Cyrillic) - Serbia", 32, "#0000ff", "", "sr-Cyrl-CS")]
		SerbianCyrillicSerbia = 3098,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Serbian (Latin) - Serbia", 33, "#0000ff", "", "sr-Latn-CS")]
		SerbianLatinSerbia = 2074,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Slovak - Slovakia", 34, "#0000ff", "", "sk-SK")]
		SlovakSlovakia = 1051,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Slovenian - Slovenia", 35, "#0000ff", "", "sl-SI")]
		SlovenianSlovenia = 1060,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Spanish - Spain", 36, "#0000ff", "", "es-ES")]
		SpanishSpain = 3082,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Swedish - Sweden", 37, "#0000ff", "", "sv-SE")]
		SwedishSweden = 1053,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Thai - Thailand", 38, "#0000ff", "", "th-TH")]
		ThaiThailand = 1054,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Turkish - Turkey", 39, "#0000ff", "", "tr-TR")]
		TurkishTurkey = 1055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ukrainian - Ukraine", 40, "#0000ff", "", "uk-UA")]
		UkrainianUkraine = 1058,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vietnamese - Vietnam", 41, "#0000ff", "", "vi-VN")]
		VietnameseVietnam = 1066,
	}
}
#pragma warning restore CS1591
