#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MsdynCrm_MatchingStrategy_Target
	{
		
		/// <summary>
		/// Contact
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Contact", 0, "#0000ff", "Contact")]
		Contact = 192350000,
		
		/// <summary>
		/// Lead
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lead", 1, "#0000ff", "Lead")]
		Lead = 192350001,
	}
}
#pragma warning restore CS1591
