#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Purpose
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MsdynCrm_MarketingPage_Purpose
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Collateral download", 3, "#0000ff")]
		CollateralDownload = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Contact capture", 0, "#0000ff")]
		ContactCapture = 0,
		
		/// <summary>
		/// Double opt-in, email-based confirmation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Double Opt-In, Email based confirmation", 7, "#0000ff", "Double opt-in, email-based confirmation")]
		DoubleOptInEmailBasedConfirmation = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Event feedback", 5, "#0000ff")]
		EventFeedback = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Event registration", 4, "#0000ff")]
		EventRegistration = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Lead generation", 2, "#0000ff")]
		LeadGeneration = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Newsletter subscription", 1, "#0000ff")]
		NewsletterSubscription = 1,
		
		/// <summary>
		/// Structural
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Structural", 6, "#0000ff", "Structural")]
		Structural = 6,
	}
}
#pragma warning restore CS1591
