#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Optimized for
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MsdynCrm_MarketingPage_OptimizedFor
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Desktop", 0, "#0000ff")]
		Desktop = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mobile", 2, "#0000ff")]
		Mobile = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tablet", 1, "#0000ff")]
		Tablet = 1,
	}
}
#pragma warning restore CS1591
