#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Bot Session Outcome option
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_SessionOutcome
	{
		
		/// <summary>
		/// Bot Session is abandoned
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("abandoned", 3, null, "Bot Session is abandoned")]
		Abandoned = 419550003,
		
		/// <summary>
		/// Bot Session is escalated
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("escalated", 2, null, "Bot Session is escalated")]
		Escalated = 419550002,
		
		/// <summary>
		/// None
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("none", 0, null, "None")]
		None = 419550000,
		
		/// <summary>
		/// Bot Session is resolved
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("resolved", 1, null, "Bot Session is resolved")]
		Resolved = 419550001,
	}
}
#pragma warning restore CS1591
