#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Sequence Step Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_SequenceStep_Type
	{
		
		/// <summary>
		/// Automatic action step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Auto action", 7, "#0000ff", "Automatic action step")]
		AutoAction = 4,
		
		/// <summary>
		/// Automated Email step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Automated Email", 6, "#0000ff", "Automated Email step")]
		AutomatedEmail = 3,
		
		/// <summary>
		/// Automated Experimentation step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Automated Experimentation", 10, "#0000ff", "Automated Experimentation step")]
		AutomatedExperimentation = 7,
		
		/// <summary>
		/// Automated text message step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Automated text message", 9, "#0000ff", "Automated text message step")]
		AutomatedTextMessage = 6,
		
		/// <summary>
		/// Competitor
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Competitor", 15, "#0000ff", "Competitor")]
		Competitor = 12,
		
		/// <summary>
		/// Email Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email", 3, "#0000ff", "Email Step")]
		Email = 4202,
		
		/// <summary>
		/// EmailValidation
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EmailValidation", 11, "#0000ff", "EmailValidation")]
		Emailvalidation = 8,
		
		/// <summary>
		/// Engage
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Engage", 14, "#0000ff", "Engage")]
		Engage = 11,
		
		/// <summary>
		/// Handover
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Handover", 17, "#0000ff", "Handover")]
		Handover = 14,
		
		/// <summary>
		/// LinkedIn action step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("LinkedIn action", 8, "#0000ff", "LinkedIn action step")]
		LinkedInAction = 5,
		
		/// <summary>
		/// Outreach
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Outreach", 13, "#0000ff", "Outreach")]
		Outreach = 10,
		
		/// <summary>
		/// Phone call step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Phone call", 4, "#0000ff", "Phone call step")]
		PhoneCall = 4210,
		
		/// <summary>
		/// Research
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Research", 12, "#0000ff", "Research")]
		Research = 9,
		
		/// <summary>
		/// Simple Condition Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Simple Condition", 0, "#0000ff", "Simple Condition Step")]
		SimpleCondition = 1,
		
		/// <summary>
		/// Stakeholder
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Stakeholder", 16, "#0000ff", "Stakeholder")]
		Stakeholder = 13,
		
		/// <summary>
		/// Task Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Task", 1, "#0000ff", "Task Step")]
		Task = 4212,
		
		/// <summary>
		/// Text message step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Text message", 2, "#0000ff", "Text message step")]
		TextMessage = 4213,
		
		/// <summary>
		/// Wait Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Wait", 5, "#0000ff", "Wait Step")]
		Wait = 0,
	}
}
#pragma warning restore CS1591
