#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_CI_Locale
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-ae", 13, "#0000ff")]
		ArAe = 140,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-bh", 14, "#0000ff")]
		ArBh = 150,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-eg", 15, "#0000ff")]
		ArEg = 160,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-iq", 16, "#0000ff")]
		ArIq = 170,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-jo", 17, "#0000ff")]
		ArJo = 180,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-kw", 18, "#0000ff")]
		ArKw = 190,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-lb", 19, "#0000ff")]
		ArLb = 200,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-om", 20, "#0000ff")]
		ArOm = 210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-qa", 21, "#0000ff")]
		ArQa = 220,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-sa", 22, "#0000ff")]
		ArSa = 230,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ar-sy", 23, "#0000ff")]
		ArSy = 240,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("cs-cz", 30, "#0000ff")]
		CsCz = 310,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("da-dk", 25, "#0000ff")]
		DaDk = 260,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("de-de", 2, "#0000ff")]
		DeDe = 20,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("el-gr", 29, "#0000ff")]
		ElGr = 300,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("en-gb", 1, "#0000ff")]
		EnGb = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("en-us", 0, "#0000ff")]
		EnUs = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("es-es", 5, "#0000ff")]
		EsEs = 50,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("es-mx", 6, "#0000ff")]
		EsMx = 60,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("fi-fi", 27, "#0000ff")]
		FiFi = 280,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("fr-ca", 11, "#0000ff")]
		FrCa = 120,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("fr-fr", 3, "#0000ff")]
		FrFr = 30,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("he-il", 24, "#0000ff")]
		HeIl = 250,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("it-it", 4, "#0000ff")]
		ItIt = 40,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ja-jp", 7, "#0000ff")]
		JaJp = 70,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ko-kr", 31, "#0000ff")]
		KoKr = 320,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("nb-no", 28, "#0000ff")]
		NbNo = 290,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("nl-nl", 10, "#0000ff")]
		NlNl = 110,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("pl-pl", 32, "#0000ff")]
		PlPl = 330,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("pt-br", 8, "#0000ff")]
		PtBr = 80,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("pt-pt", 12, "#0000ff")]
		PtPt = 130,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ru-ru", 33, "#0000ff")]
		RuRu = 340,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("sv-se", 26, "#0000ff")]
		SvSe = 270,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("th-th", 34, "#0000ff")]
		ThTh = 350,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("tr-tr", 35, "#0000ff")]
		TrTr = 360,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("zh-cn", 9, "#0000ff")]
		ZhCn = 90,
	}
}
#pragma warning restore CS1591
