#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Position for collections of information
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_VisualizationConfigType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Configuration 1", 0, "#0000ff")]
		Configuration1 = 192350000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Configuration 2", 1, "#0000ff")]
		Configuration2 = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Configuration 3", 2, "#0000ff")]
		Configuration3 = 192350002,
	}
}
#pragma warning restore CS1591
