#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_LiveWorkItemEventType
	{
		
		/// <summary>
		/// This event is triggered when the chat context is updated.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ContextUpdated", 2, "#0000ff", "This event is triggered when the chat context is updated.")]
		Contextupdated = 192350002,
		
		/// <summary>
		/// This event is triggered when a customer initiates a conversation, that is when a live work item is created.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Created", 1, "#0000ff", "This event is triggered when a customer initiates a conversation, that is when a " +
			"live work item is created.")]
		Created = 192350001,
		
		/// <summary>
		/// This event is triggered when a chat is rejoined.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("CustomerRejoin", 3, "#0000ff", "This event is triggered when a chat is rejoined.")]
		Customerrejoin = 192350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Default", 0, "#0000ff")]
		Default = 192350000,
		
		/// <summary>
		/// This event is triggered when a skill is updated during chat.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SkillIdentified", 4, "#0000ff", "This event is triggered when a skill is updated during chat.")]
		Skillidentified = 192350005,
	}
}
#pragma warning restore CS1591
