#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_TimeTrackerReasonCategoryOptionSet
	{
		
		/// <summary>
		/// Collaboration
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Collaboration", 1, null, "Collaboration")]
		Collaboration = 1,
		
		/// <summary>
		/// External Tool
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("External Tool", 2, null, "External Tool")]
		ExternalTool = 2,
		
		/// <summary>
		/// Miscellaneous
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Miscellaneous", 3, null, "Miscellaneous")]
		Miscellaneous = 3,
		
		/// <summary>
		/// Research
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Research", 0, null, "Research")]
		Research = 0,
	}
}
#pragma warning restore CS1591
