#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_SalesMicroAgentType
	{
		
		/// <summary>
		/// DCA that handles the customer engagement.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DCA Engage agent", 7, "#6A1B9A", "DCA that handles the customer engagement.")]
		DcaEngageAgent = 8,
		
		/// <summary>
		/// DCA that handles the outreach emails.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DCA Outreach agent", 6, "#6A1B9A", "DCA that handles the outreach emails.")]
		DcaOutreachAgent = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DCA_ResearchAgent", 4, "#0000ff")]
		DcaResearchagent = 5,
		
		/// <summary>
		/// Email validation agent
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email validation agent", 8, "#6A1B9A", "Email validation agent")]
		EmailValidationAgent = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("EngageAgent", 2, "#0000ff")]
		Engageagent = 3,
		
		/// <summary>
		/// Microagent that handles the Handover process for Sales Agent.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Handover Microagent", 5, "#6A1B9A", "Microagent that handles the Handover process for Sales Agent.")]
		HandoverMicroagent = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("LeadReadinessAgent", 3, "#0000ff")]
		Leadreadinessagent = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("OutreachAgent", 1, "#0000ff")]
		Outreachagent = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("ResearchAgent", 0, "#0000ff")]
		Researchagent = 1,
	}
}
#pragma warning restore CS1591
