#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Portal installation status
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MsdynCrm_MarketingPageConfiguration_MsdynCrm_PortalInstallationStatus
	{
		
		/// <summary>
		/// Failed
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Failed", 2, "#0000ff", "Failed")]
		Failed = 3,
		
		/// <summary>
		/// Not started
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not started", 0, "#0000ff", "Not started")]
		NotStarted = 1,
		
		/// <summary>
		/// Started
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Started", 1, "#0000ff", "Started")]
		Started = 2,
	}
}
#pragma warning restore CS1591
