#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Authentication Types
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_OCAuthenticationType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("OAuth 2.0 Code flow", 0, "#0000ff")]
		Oauth20CodeFlow = 192350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("OAuth 2.0 implicit flow", 1, "#0000ff")]
		Oauth20ImplicitFlow = 192350000,
	}
}
#pragma warning restore CS1591
