#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MsDynMkt_Source
	{
		
		/// <summary>
		/// Internal – Created manually or changed in the application
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Internal", 0, "#0000ff", "Internal – Created manually or changed in the application")]
		Internal = 534120000,
		
		/// <summary>
		/// Preference page - updated by customer
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Preference page", 1, "#0000ff", "Preference page - updated by customer")]
		PreferencePage = 534120001,
		
		/// <summary>
		/// Text message - updated by customer via text message
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Text message", 2, "#0000ff", "Text message - updated by customer via text message")]
		TextMessage = 534120002,
	}
}
#pragma warning restore CS1591
