#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Defines type of the diagnostics record
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_UnifiedRoutingDiagnostic_Msdyn_DiagnosticDataType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Assignment Diagnostic", 4, "#0000ff")]
		AssignmentDiagnostic = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Demand Classification Diagnostic", 2, "#0000ff")]
		DemandClassificationDiagnostic = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Demand ML Diagnostic", 1, "#0000ff")]
		DemandMlDiagnostic = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Demand RTQ Diagnostic", 3, "#0000ff")]
		DemandRtqDiagnostic = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Unknown", 0, "#0000ff")]
		Unknown = 0,
	}
}
#pragma warning restore CS1591
