#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Sequence Step Sub Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_SequenceStep_Subtype
	{
		
		/// <summary>
		/// Advance To Other Sequence
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("AdvanceToOtherSequence", 5, "#0000ff", "Advance To Other Sequence")]
		Advancetoothersequence = 5,
		
		/// <summary>
		/// Default
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Default", 0, "#0000ff", "Default")]
		Default = 0,
		
		/// <summary>
		/// LinkedIn Action Connect Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("LinkedInConnect", 3, "#0000ff", "LinkedIn Action Connect Step")]
		LinkedInconnect = 3,
		
		/// <summary>
		/// LinkedIn Action Get Introduced Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("LinkedInGetIntroduced", 2, "#0000ff", "LinkedIn Action Get Introduced Step")]
		LinkedIngetintroduced = 2,
		
		/// <summary>
		/// LinkedIn Action InMail Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("LinkedInMail", 4, "#0000ff", "LinkedIn Action InMail Step")]
		LinkedInmail = 4,
		
		/// <summary>
		/// LinkedIn Action Research Step
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("LinkedInResearch", 1, "#0000ff", "LinkedIn Action Research Step")]
		LinkedInresearch = 1,
	}
}
#pragma warning restore CS1591
