#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Visual style
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MsdynCrm_MarketingPage_VisualStyle
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Colorful", 2, "#0000ff")]
		Colorful = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dark", 1, "#0000ff")]
		Dark = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Light", 0, "#0000ff")]
		Light = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 3, "#0000ff")]
		Other = 3,
	}
}
#pragma warning restore CS1591
