#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Visual style
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MsdynCrm_Email_Template_Visual_Style
	{
		
		/// <summary>
		/// Colorful
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Colorful", 2, "#0000ff", "Colorful")]
		Colorful = 2,
		
		/// <summary>
		/// Dark
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dark", 3, "#0000ff", "Dark")]
		Dark = 3,
		
		/// <summary>
		/// Light
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Light", 1, "#0000ff", "Light")]
		Light = 1,
		
		/// <summary>
		/// Other
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 0, "#0000ff", "Other")]
		Other = 0,
	}
}
#pragma warning restore CS1591
