#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Defines the type of the dataverse component being used in the ruleset
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_DatAverseComponentType
	{
		
		/// <summary>
		/// Routing using the custom API
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Custom API", 1, null, "Routing using the custom API")]
		CustomApi = 192350000,
		
		/// <summary>
		/// Unknown
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Unkown", 0, null, "Unknown")]
		Unkown = 0,
	}
}
#pragma warning restore CS1591
