#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// behaviour of the solution
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Msdyn_SolutionBehaviour
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Global", 0)]
		Global = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Intent", 1)]
		Intent = 100000001,
	}
}
#pragma warning restore CS1591
