#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Possible state for a feature
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MsdynCrm_Feature_State_Option_Set
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Disabled", 1, "#0000ff")]
		Disabled = 192350020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Enabled", 0, "#0000ff")]
		Enabled = 192350010,
	}
}
#pragma warning restore CS1591
