#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MsDynMkt_TimeZoneType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("A specific timezone", 0, "#0000ff")]
		ASpecificTimezone = 534120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("The time zone of the user who creates the journey", 1, "#0000ff")]
		TheTimeZoneOfTheUserWhoCreatesTheJourney = 534120001,
	}
}
#pragma warning restore CS1591
