#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MsDynMkt_DoIJobStatus_OptionSet
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email Created", 1, "#0000ff")]
		EmailCreated = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email Create Failed", 8, "#0000ff")]
		EmailCreateFailed = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email Published", 2, "#0000ff")]
		EmailPublished = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Email Publish Failed", 9, "#0000ff")]
		EmailPublishFailed = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Failed", 7, "#0000ff")]
		Failed = 7,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Journey Created", 3, "#0000ff")]
		JourneyCreated = 3,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Journey Create Failed", 10, "#0000ff")]
		JourneyCreateFailed = 10,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Journey Published", 5, "#0000ff")]
		JourneyPublished = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Journey Publish Failed", 11, "#0000ff")]
		JourneyPublishFailed = 11,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Journey Publishing Started", 4, "#0000ff")]
		JourneyPublishingStarted = 4,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Processing Completed", 6, "#0000ff")]
		ProcessingCompleted = 6,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Request Accepted", 0, "#0000ff")]
		RequestAccepted = 0,
	}
}
#pragma warning restore CS1591
