#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Square units
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MSeVTmGt_SquareUnits
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sq. feet", 1, "#0000ff")]
		SqFeet = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Sq. meters", 0, "#0000ff")]
		SqMeters = 100000000,
	}
}
#pragma warning restore CS1591
