#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Gender
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MSeVTmGt_Gender
	{
		
		/// <summary>
		/// Female
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Female", 1, "#0000ff", "Female")]
		Female = 100000001,
		
		/// <summary>
		/// Male
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Male", 0, "#0000ff", "Male")]
		Male = 100000000,
	}
}
#pragma warning restore CS1591
