#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Available event creation origins
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MSeVTmGt_SourceSystem
	{
		
		/// <summary>
		/// Outbound marketing
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Outbound marketing", 0, "#0000ff", "Outbound marketing")]
		OutboundMarketing = 100000001,
		
		/// <summary>
		/// Real-time Journeys
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Real-time Journeys", 1, "#0000ff", "Real-time Journeys")]
		RealTimeJourneys = 100000002,
	}
}
#pragma warning restore CS1591
