#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Available streaming providers
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MSeVTmGt_StreamingProvider
	{
		
		/// <summary>
		/// Other
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 5, "#0000ff", "Other")]
		Other = 100000003,
		
		/// <summary>
		/// Teams Live Events
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Teams Live Events", 2, "#0000ff", "Teams Live Events")]
		TeamsLiveEvents = 100000001,
		
		/// <summary>
		/// Teams Meetings
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Teams Meetings", 3, "#0000ff", "Teams Meetings")]
		TeamsMeetings = 100000002,
		
		/// <summary>
		/// Teams Town Hall
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Teams Town Hall", 4, "#0000ff", "Teams Town Hall")]
		TeamsTownHall = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Teams Virtual Events", 1, "#0000ff")]
		TeamsVirtualEvents = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Teams Webinars", 0, "#0000ff")]
		TeamsWebinars = 100000004,
	}
}
#pragma warning restore CS1591
