#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Publish status
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MSeVTmGt_PublishStatus
	{
		
		/// <summary>
		/// Cancelled
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cancelled", 4, "#0000ff", "Cancelled")]
		Cancelled = 100000004,
		
		/// <summary>
		/// Draft
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Draft", 0, "#0000ff", "Draft")]
		Draft = 100000000,
		
		/// <summary>
		/// Going live
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Going live", 5, "#0000ff", "Going live")]
		GoingLive = 100000005,
		
		/// <summary>
		/// In progress
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("In progress", 2, "#0000ff", "In progress")]
		InProgress = 100000002,
		
		/// <summary>
		/// Live
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Live", 3, "#0000ff", "Live")]
		Live = 100000003,
		
		/// <summary>
		/// Ready to go live
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ready to go live", 1, "#0000ff", "Ready to go live")]
		ReadyToGoLive = 100000001,
	}
}
#pragma warning restore CS1591
