#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum MSeVTmGt_AutoAdmittedUsers
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Everyone", 2, "#0000ff")]
		Everyone = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Only me", 4, "#0000ff")]
		OnlyMe = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("People I invite", 3, "#0000ff")]
		PeopleIInvite = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("People in my organization and guests", 0, "#0000ff")]
		PeopleInMyOrganizationAndGuests = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("People in my organization, trusted organizations and guests", 1, "#0000ff")]
		PeopleInMyOrganizationTrustedOrganizationsAndGuests = 100000002,
	}
}
#pragma warning restore CS1591
