#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Specifies whether the property is in Edit or Rectify mode.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum QooiProduct_PropertiesConfigurationStatus
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Edit", 0)]
		Edit = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Not Configured", 2)]
		NotConfigured = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Rectify", 1)]
		Rectify = 1,
	}
}
#pragma warning restore CS1591
