#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Based on the options in SkipPriceCalculation , OOB price calculation for  qooi level will be skipped
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum QOOI_SkipPriceCalculation
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("DoPriceCalcAlways", 0)]
		Dopricecalcalways = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("SkipPriceCalcOnRetrieve", 1)]
		Skippricecalconretrieve = 1,
	}
}
#pragma warning restore CS1591
