#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Select criteria for the selection rule
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum Selection_Rule_Criteria
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Least Busy", 1)]
		LeastBusy = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Most Busy", 2)]
		MostBusy = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Random (default)", 0)]
		RandomDefault = 0,
	}
}
#pragma warning restore CS1591
