#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum WKCDA_CancelReason
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Black Rainstorm Warning Signal ", 4)]
		BlackRainstormWarningSignal = 372120004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" No.3 Strong Wind Signal ", 1)]
		No3StrongWindSignal = 372120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" No.8 Gale/Storm Signal ", 2)]
		No8GaleStormSignal = 372120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Not Enough Customer Registered ", 5)]
		NotEnoughCustomerRegistered = 372120005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Other Reason ", 6)]
		OtherReason = 372120006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Red Rainstorm Warning Signal ", 3)]
		RedRainstormWarningSignal = 372120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("To Be Rescheduled ", 0)]
		ToBeRescheduled = 372120000,
	}
}
#pragma warning restore CS1591
