#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum WKCDA_CaseCategory
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Acquire contact of other dept./ staff ", 0)]
		AcquireContactOfOtherDeptStaff = 372120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Adverse weather arrangement ", 1)]
		AdverseWeatherArrangement = 372120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Autonomous vehicle ", 2)]
		AutonomousVehicle = 372120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Business opportunity ", 3)]
		BusinessOpportunity = 372120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Crowd / Queuing control ", 4)]
		CrowdQueuingControl = 372120004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Development plan of West Kowloon", 50)]
		DevelopmentPlanOfWestKowloon = 372120050,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Donation / Sponsorship ", 5)]
		DonationSponsorship = 372120005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Exhibition / Gallery Information ", 6)]
		ExhibitionGalleryInformation = 372120006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Facility management ", 8)]
		FacilityManagement = 372120008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" F&B service ", 7)]
		FBService = 372120007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Filming / Photo shooting ", 9)]
		FilmingPhotoShooting = 372120009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Forward to reception ", 10)]
		ForwardToReception = 372120010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Forward to ticketing ", 11)]
		ForwardToTicketing = 372120011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Forward to venue hire ", 12)]
		ForwardToVenueHire = 372120012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" HR - career opportunity ", 13)]
		HrCareerOpportunity = 372120013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" HR - others ", 14)]
		HrOthers = 372120014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Invitation to WKCDA staff ", 15)]
		InvitationToWkcdaStaff = 372120015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Leasing ", 16)]
		Leasing = 372120016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Lost & Found ", 17)]
		LostFound = 372120017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Media enquiry ", 18)]
		MediaEnquiry = 372120018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Membership ", 19)]
		Membership = 372120019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Miscellaneous ", 20)]
		Miscellaneous = 372120020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Nuisance / Prank call ", 21)]
		NuisancePrankCall = 372120021,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Opening arrangement ", 22)]
		OpeningArrangement = 372120022,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Organisation / Student research ", 23)]
		OrganisationStudentResearch = 372120023,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" PA Programme - external hire ", 24)]
		PaProgrammeExternalHire = 372120024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" PA Programme - internal organise ", 25)]
		PaProgrammeInternalOrganise = 372120025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Programme arrangement under special situation ", 30)]
		ProgrammeArrangementUnderSpecialSituation = 372120030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Programme - external hire ", 26)]
		ProgrammeExternalHire = 372120026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Programme - internal organise ", 27)]
		ProgrammeInternalOrganise = 372120027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Programme - learning & participation ", 28)]
		ProgrammeLearningParticipation = 372120028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Programme - others ", 29)]
		ProgrammeOthers = 372120029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Request for visit ", 31)]
		RequestForVisit = 372120031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Retail service ", 32)]
		RetailService = 372120032,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Rules & Regulations ", 33)]
		RulesRegulations = 372120033,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Safety ", 34)]
		Safety = 372120034,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Show quality of programme / show ", 35)]
		ShowQualityOfProgrammeShow = 372120035,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Show quality of signage ", 36)]
		ShowQualityOfSignage = 372120036,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" SmartBike ", 37)]
		Smartbike = 372120037,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Staff attitude / Skillset ", 38)]
		StaffAttitudeSkillset = 372120038,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Street performance ", 39)]
		StreetPerformance = 372120039,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tender / Procurement", 40)]
		TenderProcurement = 372120040,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ticket - pricing", 41)]
		TicketPricing = 372120041,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ticket - promotion", 42)]
		TicketPromotion = 372120042,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ticket - purchase method", 43)]
		TicketPurchaseMethod = 372120043,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ticket - transaction issue", 44)]
		TicketTransactionIssue = 372120044,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transportation & Parking", 45)]
		TransportationParking = 372120045,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Travel Group / School visit", 46)]
		TravelGroupSchoolVisit = 372120046,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Venue hire", 47)]
		VenueHire = 372120047,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Visitors interface technology", 48)]
		VisitorsInterfaceTechnology = 372120048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Volunteer/ Docent Programme", 49)]
		VolunteerDocentProgramme = 372120049,
	}
}
#pragma warning restore CS1591
