#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum WKCDA_Interest
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Dining", 10)]
		Dining = 372120010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Family Events ", 4)]
		FamilyEvents = 372120004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Free Events ", 3)]
		FreeEvents = 372120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Guided Tour ", 0)]
		GuidedTour = 372120000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" I\'m a tourist ", 7)]
		IMATourist = 372120007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Pets Friendly Activities ", 5)]
		PetsFriendlyActivities = 372120005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Shopping ", 6)]
		Shopping = 372120006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Supporting West Kowloon ", 9)]
		SupportingWestKowloon = 372120009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Talks / Seminars ", 2)]
		TalksSeminars = 372120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Volunteer / Docent Opportunities ", 8)]
		VolunteerDocentOpportunities = 372120008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute(" Workshop ", 1)]
		Workshop = 372120001,
	}
}
#pragma warning restore CS1591
