#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum WKCDA_Accessibility
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Accessible parking space", 6, "#0000ff")]
		AccessibleParkingSpace = 372120006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Aisle seat", 2, "#0000ff")]
		AisleSeat = 372120002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Audio Description", 3, "#0000ff")]
		AudioDescription = 372120003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other access requirements or preference", 7, "#0000ff")]
		OtherAccessRequirementsOrPreference = 372120007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Request for accessible information", 8, "#0000ff")]
		RequestForAccessibleInformation = 372120008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Require assistance of Accessibility Ambassador", 4, "#0000ff")]
		RequireAssistanceOfAccessibilityAmbassador = 372120004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Room for assistance dog", 5, "#0000ff")]
		RoomForAssistanceDog = 372120005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Theatrical Interpretation / Sign Interpretation", 1, "#0000ff")]
		TheatricalInterpretationSignInterpretation = 372120001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Wheelchair Seats", 0, "#0000ff")]
		WheelchairSeats = 372120000,
	}
}
#pragma warning restore CS1591
